In [1]:
import numpy as np

In [2]:
mylist1=[1,2,3]

In [3]:
myarray1=np.array(mylist1)


In [4]:
myarray1

array([1, 2, 3])

In [5]:
mylist2=[11,22,33]

In [6]:
mylists=[mylist1,mylist2]

In [7]:
myarray2=np.array(mylist2)

In [8]:
myarray2

array([11, 22, 33])

In [9]:
myarray2=np.array(mylists)

In [10]:
myarray2

array([[ 1,  2,  3],
       [11, 22, 33]])

In [11]:
myarray2.shape

(2L, 3L)

In [12]:
myarray2.dtype

dtype('int32')

In [13]:
np.zeroes[5]

AttributeError: 'module' object has no attribute 'zeroes'

In [14]:
np.zeroes(5)

AttributeError: 'module' object has no attribute 'zeroes'

In [15]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
my_zero_array=np.zeros(5)

In [17]:
my_zero_array

array([ 0.,  0.,  0.,  0.,  0.])

In [18]:
my_zero_array.dtype


dtype('float64')

In [19]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [20]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [21]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])