In [1]:
import numpy as np

In [2]:
arr=np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myarray',arr)

In [5]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [6]:
arr1=np.arange(10)

In [8]:
arr2=np.arange(5)

In [10]:
np.savez('myarrayzip.npz',x=arr1,y=arr2)

In [11]:
archive_array=np.load('myarrayzip.npz')

In [13]:
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
archive_array['y']

array([0, 1, 2, 3, 4])

In [16]:
arrtxt=np.array([[1,2,3,4],[5,6,7,8]])

In [17]:
np.savetxt('myarraytxt.txt',arrtxt,delimiter=',')

In [19]:
arr3=np.loadtxt('myarraytxt.txt',delimiter=',')

In [20]:
arr3

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.]])