In [1]:
import numpy as np

In [2]:
arr=np.arange(50)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [4]:
arr=arr.reshape([5,10])

In [5]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [6]:
arr.T

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44],
       [ 5, 15, 25, 35, 45],
       [ 6, 16, 26, 36, 46],
       [ 7, 17, 27, 37, 47],
       [ 8, 18, 28, 38, 48],
       [ 9, 19, 29, 39, 49]])

In [7]:
np.dot(arr.T,arr)
#dot product of matrices

array([[3000, 3100, 3200, 3300, 3400, 3500, 3600, 3700, 3800, 3900],
       [3100, 3205, 3310, 3415, 3520, 3625, 3730, 3835, 3940, 4045],
       [3200, 3310, 3420, 3530, 3640, 3750, 3860, 3970, 4080, 4190],
       [3300, 3415, 3530, 3645, 3760, 3875, 3990, 4105, 4220, 4335],
       [3400, 3520, 3640, 3760, 3880, 4000, 4120, 4240, 4360, 4480],
       [3500, 3625, 3750, 3875, 4000, 4125, 4250, 4375, 4500, 4625],
       [3600, 3730, 3860, 3990, 4120, 4250, 4380, 4510, 4640, 4770],
       [3700, 3835, 3970, 4105, 4240, 4375, 4510, 4645, 4780, 4915],
       [3800, 3940, 4080, 4220, 4360, 4500, 4640, 4780, 4920, 5060],
       [3900, 4045, 4190, 4335, 4480, 4625, 4770, 4915, 5060, 5205]])

In [8]:
#3 dimensnal matrix

In [17]:
arr3d=np.arange(40).reshape(2,10,2)
# 2*10*2=40

In [18]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [28]:
arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [20, 21]],

       [[ 2,  3],
        [22, 23]],

       [[ 4,  5],
        [24, 25]],

       [[ 6,  7],
        [26, 27]],

       [[ 8,  9],
        [28, 29]],

       [[10, 11],
        [30, 31]],

       [[12, 13],
        [32, 33]],

       [[14, 15],
        [34, 35]],

       [[16, 17],
        [36, 37]],

       [[18, 19],
        [38, 39]]])

In [33]:
arr.swapaxes(1,0)
#similar to transpose

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44],
       [ 5, 15, 25, 35, 45],
       [ 6, 16, 26, 36, 46],
       [ 7, 17, 27, 37, 47],
       [ 8, 18, 28, 38, 48],
       [ 9, 19, 29, 39, 49]])