In [1]:
import numpy as np

In [2]:
5/2

2

In [3]:
5.0/2

2.5

In [4]:
import _future_division

ImportError: No module named _future_division

In [5]:
from __future__ import division

In [6]:
5/2

2.5

In [8]:
arr1=np.array([[1,2,3,4],[11,22,33,44]])

In [9]:
arr1

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [10]:
arr1*arr1

array([[   1,    4,    9,   16],
       [ 121,  484, 1089, 1936]])

In [11]:
arr1-2

array([[-1,  0,  1,  2],
       [ 9, 20, 31, 42]])

In [12]:
arr1+3

array([[ 4,  5,  6,  7],
       [14, 25, 36, 47]])

In [13]:
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
arr1/2

array([[  0.5,   1. ,   1.5,   2. ],
       [  5.5,  11. ,  16.5,  22. ]])

In [15]:
arr1**2

array([[   1,    4,    9,   16],
       [ 121,  484, 1089, 1936]])