In [1]:
import numpy as np

In [2]:
arr=np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr.sqrt(arr)

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [5]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [7]:
#call functions refering to numpy library instance np

In [8]:
a=np.random.randn(10)

In [9]:
a

array([ 0.3736409 , -1.1466785 , -0.84750351, -0.15088982,  0.47035943,
       -1.07412039,  0.3219771 , -1.79512381, -0.66114326, -1.54372293])

In [10]:
b=np.random.randn(10)

In [11]:
b

array([-1.54465946, -0.0484786 ,  0.39476638, -1.8661606 ,  0.13435196,
        0.47787706,  1.6187487 , -0.59885013, -0.16807904, -0.36297934])

In [12]:
np.add(a,b)

array([-1.17101856, -1.1951571 , -0.45273713, -2.01705042,  0.60471139,
       -0.59624333,  1.94072581, -2.39397394, -0.8292223 , -1.90670227])

In [13]:
np.maximum(a,b)
#gets max from a and b array

array([ 0.3736409 , -0.0484786 ,  0.39476638, -0.15088982,  0.47035943,
        0.47787706,  1.6187487 , -0.59885013, -0.16807904, -0.36297934])

In [14]:
website='http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser

In [15]:
webbrowser.open(website)

True